---
name: xyzzy

# https://docs.docker.com/compose/compose-file/07-volumes/
volumes:
  # by default volume in docker api are prefixed with compose "name"
  # lets create a simple volume
  data-volume:
  # we can also specify what name the volume should have in docker api
  # name some-other-random-name will be listed in `docker volume ls`
  backup-volume:
    name: some-other-random-name
  # we can reference a volume that was created outside compose
  db-volume:
    external:
      name: external-volume-created-outside-compose

# https://docs.docker.com/reference/compose-file/networks/
networks:
  some_network:
    name: this_is_going_to_be_an_actual_name

# to use external network
#networks:
#  already_existing_external_network:
#    external: true

# https://docs.docker.com/reference/compose-file/services/
services:
  nginx:
    container_name: my_custom_name

    image: nginx:1.26
    entrypoint:
      - sleep
    command:
      - infinity
    restart: unless-stopped

    privileged: false

    # i do this for promtail see promtail for more details about it
    logging:
      options:
        tag: "{{ .Name }}"
        labels: stack

    # https://docs.docker.com/reference/compose-file/services/#network_mode
    network_mode: host # to use `host` network namespace
                       # or `none` - to disable container networking at all

    # if you use non DEFAULT network
    networks:
      - this_is_going_to_be_an_actual_name

    # https://docs.docker.com/reference/compose-file/services/#ports
    ports:
      # long version:
      # - HOST_IP:HOST_PORT:CONTAINER_PORT/PROTOCOL
      # - 127.0.0.1:9090:8080/tcp
      # short version:
      # - HOST_PORT:CONTAINER_PORT
      - 9090:8080

    # https://docs.docker.com/reference/compose-file/services/#volumes
    volumes:
      - type: volume
        source: backup-volume
        target: /tmp/backup
      # short version of it would be:
      # - backup-volume:/tmp/backup
      - type: bind
        source: ./path/in/local/filesystem
        target: /data
        read_only: true
      # short version of it would be:
      # - ./path/in/local/filesystem:/data:ro

    labels:
      stack: whatever
